apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-dashboard
  - monitoring
  - coredns/
  - externaldns/
  - fireflyiii/
  - mixpost/
  - zt-edge-gateway/
  - vaultwarden/
  - shared-helm.yaml
