apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd-operator
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/k3s/etcd-operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m

