apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-controller
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/k3s/nginx-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium
  timeout: 10m
