apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: dns-etcd
  namespace: network-dns
spec:
  version: v3.6.0-rc.3
  size: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dns-etcd-client
  namespace: network-dns
  labels:
    app: dns-etcd
spec:
  type: ClusterIP
  clusterIP: 10.43.93.200
  ports:
  - name: client
    port: 2379
    targetPort: 2379
    protocol: TCP
  selector:
    app: dns-etcd
  