apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: dns-ectd
  namespace: network-dns
spec:
  size: 3
  version: 3.4.13
  pod:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  backup:
    enabled: true
    intervalInSecond: 3600
    retention: 24h
    storageType: persistentVolume
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
