apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: dns-etcd
  namespace: network-dns
spec:
  version: v3.6.0-rc.3
  size: 3
  # pod:
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
  #     limits:
  #       cpu: 200m
  #       memory: 256Mi
  # backup:
  #   enabled: true
  #   intervalInSecond: 3600
  #   retention: 24h
  #   storageType: persistentVolume
  #   volumeClaimTemplate:
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dns-etcd-client
  namespace: network-dns
  labels:
    app: etcd
    etcd_cluster: dns-ectd  # Match the actual cluster name with typo for now
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2379
    targetPort: 2379
    protocol: TCP
  selector:
    app: etcd
    etcd_cluster: dns-ectd 
  