apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: etcd-operator
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: helm-stable
        namespace: default
  values:
    operator:
      createCRD: true
---
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: dns-ectd
  namespace: network-dns
spec:
  size: 3
  version: 3.4.13
  pod:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  backup:
    enabled: true
    intervalInSecond: 3600
    retention: 24h
    storageType: persistentVolume
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
