apiVersion: v1
kind: Namespace
metadata:
  name: network-dns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-resolv-conf
  namespace: network-dns
data:
  resolv.conf: |
    nameserver 10.43.0.10
    nameserver 192.168.0.1
    nameserver 75.75.75.75
    options edns0
    search network-dns.svc.cluster.local svc.cluster.local cluster.local
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: network-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: coredns
      version: "1.43.3"
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: network-dns
  values:
    serviceType: LoadBalancer
    customLabels:
      external-connection: "true"
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.6.0"
    ports:
      - name: dns
        protocol: UDP
        port: 53
      - name: dns-tcp
        protocol: TCP
        port: 53
      - name: metrics
        protocol: TCP
        port: 9153
    servers:
      - zones:
        - zone: .
        port: 53
        plugins:
          - name: errors
          - name: health
          - name: ready
          - name: loop
          - name: reload
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: cache
            parameters: 30
          - name: forward
            parameters: . /etc/coredns/resolv.conf
          - name: loadbalance
      - zones:
        - zone: home.lan.
        port: 53
        plugins:
          - name: health
          - name: ready
          - name: errors
          - name: loop
          - name: reload
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: cache
            parameters: 30
          - name: etcd
            parameters: home.lan
            configBlock: |
              endpoint http://dns-etcd-client.network-dns.svc.cluster.local:2379
              path /skydns
              fallthrough
    prometheus:
      monitoring:
        enabled: true
    extraVolumes:
      - name: custom-resolv
        configMap:
          name: custom-resolv-conf
          items:
            - key: resolv.conf
              path: resolv.conf
    
    # Mount the volume
    extraVolumeMounts:
      - name: custom-resolv
        mountPath: /etc/coredns/resolv.conf
        subPath: resolv.conf
        readOnly: true