
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/k3s/apps/coredns/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: etcd-operator
  # Add health checks to ensure CRDs are established
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: etcdclusters.etcd.database.coreos.com
--- 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-dns

resources:
  - helm-repo.yaml
  - helm-coredns.yaml
  - helm-ectd.yaml

