apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.6.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    grafana:
      enabled: true
      service:
        type: LoadBalancer
        labels:
          external-connection: "true"
        annotations:
          io.cilium/lb-ipam-ips: "1"
          external-dns.alpha.kubernetes.io/hostname: "grafana.home.lan"

    prometheus:
      service:
        type: LoadBalancer
        labels:
          external-connection: "true"
        annotations:
          io.cilium/lb-ipam-ips: "1"
          external-dns.alpha.kubernetes.io/hostname: "prometheus.home.lan"
