apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.15.11"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  values:
    k8sServiceHost: "127.0.0.1"
    k8sServicePort: "6443"
    
    kubeProxyReplacement: "true"
    
    operator:
      replicas: 1
    
    ipam:
      mode: "kubernetes"
    
    routingMode: "tunnel"
    tunnelProtocol: "vxlan"
    
    # Use a different VXLAN device name to avoid conflicts
    vxlan:
      device: "cilium_vxlan2"
    
    # Clean slate configuration
    cleanState: true
    
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
