apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-values
  namespace: kube-system
data:
  values.yaml: |
    cluster:
      name: k3s-home
      id: 1
    
    k8sServiceHost: "127.0.0.1"
    k8sServicePort: "6443"
    
    kubeProxyReplacement: "strict"
    
    operator:
      replicas: 1
    
    ipam:
      mode: kubernetes
    
    tunnelProtocol: vxlan
    
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: false
    
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
