apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.15.11"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  values:
    k8sServiceHost: "127.0.0.1"
    k8sServicePort: "6443"
    
    kubeProxyReplacement: "true"
    
    operator:
      replicas: 1
    ipam:
      mode: "kubernetes"
    
    routingMode: "tunnel"
    tunnelProtocol: "geneve"
    devices:
      - eno1
      - enp1s0
    cleanState: true
    l2announcements:
      enabled: true
    k8sClientRateLimit:
      qps: 20
      burst: 30
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        service:
          type: ClusterIP
          labels:
            app: hubble-ui
            external-connection: "true"
          # Optional: You can specify a particular IP from your pool if desired
          # loadBalancerIP: "192.168.4.100"
          # Or let Cilium automatically assign one from the pool
          annotations:
            io.cilium/lb-ipam-ips: "1"

