apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-ippool"
  namespace: "kube-system"
spec:
  blocks:
    - start: "192.168.4.0"
      stop: "192.168.7.255"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2announcement-policy-external
spec:
  serviceSelector:
    matchLabels:
      external-connection: "true"
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - (^eno[0-9]+|^enp[0-9]+s[0-9]+)
  externalIPs: true
  loadBalancerIPs: true
