apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: ian@grandlan.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-cloudflare
    solvers:
      - selector:
          dnsZones:
            - grandlan.dev
        dns01:
          cloudflare:
            email: ian@grandlan.dev
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
# Create this secret outside of Flux so it is not overwritten:
# kubectl -n cert-manager create secret generic cloudflare-api-token \
#   --from-literal=api-token='<PASTE_CLOUDFLARE_API_TOKEN_FROM_CLIPBOARD>'
# Then apply or reconcile this ClusterIssuer.
