apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
  labels:
    external-connection: "true"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: firefly.home.lan
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: http
      port: 80
      targetPort: web
    - name: https
      port: 443
      targetPort: websecure